apiVersion: v1
kind: Service
metadata:
  name: {{ include "spectral.fullname" . }}-headless
  labels:
    {{- include "spectral.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      name: epmd
  selector:
    {{- include "spectral.selectorLabels" . | nindent 4 }}
